Traceback (most recent call last):
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\unerue\miniconda3\envs\vision\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
rho = 2./3
labda = 1.
mu = labda*rv.mean()/rho

mm1 = MXM1(labda, mu, rv)

for n in range(20):
    print(n, mm1.p(n), (1-rho)*rho**n)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [3][0m, in [0;36m<cell line: 5>[1;34m()[0m
[0;32m      2[0m labda [38;5;241m=[39m [38;5;241m1.[39m
[0;32m      3[0m mu [38;5;241m=[39m labda[38;5;241m*[39mrv[38;5;241m.[39mmean()[38;5;241m/[39mrho
[1;32m----> 5[0m mm1 [38;5;241m=[39m [43mMXM1[49m(labda, mu, rv)
[0;32m      7[0m [38;5;28;01mfor[39;00m n [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m20[39m):
[0;32m      8[0m     [38;5;28mprint[39m(n, mm1[38;5;241m.[39mp(n), ([38;5;241m1[39m[38;5;241m-[39mrho)[38;5;241m*[39mrho[38;5;241m*[39m[38;5;241m*[39mn)

[1;31mNameError[0m: name 'MXM1' is not defined
NameError: name 'MXM1' is not defined

